_our-achievements/2023.md
_our-community/Executive Committee.md
announcements/yishun-primary-school/_posts/2023-04-06-post-Minister of Education School Visit.md

- Added FB embedded post for Moo-o awards under Achievements 2023 page.
- Revert FB embedded post for Minister Chan School visit to it's original size under Announcements page.
- Corrected spelling error for Mr Marvin Chan's name under Executive Committee page.

20230524_Minor Website Content Updates (See description)

---

_about-us/Services In School/School Bookshop.md
_quick-links/For Parents And Students.md

- Fixed broken link for Services in School under Quick Links for Parents page.
- Corrected the Bookshop operating hours under the School Bookshop page. (Updated 27 June 2023)

20230626_Minor School Website Update (See details below)

---

_curriculum/English Language.md
_mk-at-yps/Our MK Experience/Our Achievements.md
_mk-at-yps/Our MK Experience/Our Environment.md
_mk-at-yps/collection.yml
_yps-experience/Co Curricular Activites (CCA).md
pages/MK Our Environment.md
pages/Our Environment.md

- Corrected a typo "promore" to "promote" in CCA page.
- Removed excess code "**" in English page.

20230712_School Website Updates (See Details)

---

_mk-at-yps/Our MK Experience/Our Events.md
_our-community/Non Teaching Staff.md
_our-community/Teaching Staff.md

- Added Teacher Soh Whee Kheng as FT for 1GR class in Teaching Staff page.
- Updated the Teaching Staff page according to the staff list.
- Added MK OSO Mdm Leong in Non-Teaching Staff page,
Update 28th July 2023
- Added Racial Harmony Day photos under MK Our Events page.

20230727_School Website Updates (See description below)

---

_our-community/Executive Committee.md
_our-community/Non Teaching Staff.md
_quick-links/For Parents And Students.md

- Removed Amanda Woo from EXCO and Non-Teaching Staff page.
- Added AskGov@YPS page link into Quick Links for parents page.

20230802_School Website Updates

---

_about-us/Calendar.md
_mk-at-yps/Our MK Events/Term 4.md
_mk-at-yps/Our Staff.md
_mk-at-yps/collection.yml
_our-community/Non Teaching Staff.md

- Removed Ayu's name from Non-Teaching Staff and MK Our Staff page
- Replace Google Calendar embedding to ictyishun@gmail.com account under the School Calendar pagedue to yps_admin@moe.edu.sg account set to discontinued in mid-October.

20231012_School Website Update (See Description)

---

_about-us/School Hours.md

- Amended the am and pm to a.m. and p.m. under the School Hours page.

20240102_School Website Updates

---

_mk-at-yps/Home.md

- Added the MK Open House 2024 information in the MK Home page.

20230129_School Website Updates

---

_mk-at-yps/Home.md
_mk-at-yps/MK Open House 2024.md
_mk-at-yps/collection.yml

- Added MK Open House 2024 sub-page under MK website.
- Removed Open House contents from MK Main page.

20240131_School Website Updates

---

_quick-links/For Parents And Students.md
pages/MOE Sexuality Education.md

- Updated information under MOE Sexuality Education webpage
- Updated links under the Quick Links for parents and students webpage

20240305_School Website Update

---

_our-community/Executive Committee.md
_quick-links/For Parents And Students.md

- Updated SEAB Dictionary links for 2024 under the Parents Quick Links page.
- Removed MS Kelly Tan from EXCO page.

20240326_School Website Updates

---

_ccas/Clubs/English, Drama & Debating.md
_ccas/Clubs/Environmental Science.md
_ccas/Clubs/Infocomm Technology (Computing).md
_ccas/Clubs/International Chess.md
_ccas/Sports & Games/Football.md
_ccas/Uniformed Groups/Scouts.md
_ccas/Visual & Performing Arts/Art & Crafts.md
_ccas/Visual & Performing Arts/Chinese Dance.md
_ccas/Visual & Performing Arts/Concert Band.md
_ccas/Visual & Performing Arts/Indian Dance.md
_ccas/Visual & Performing Arts/Malay Dance.md
_ccas/Visual & Performing Arts/Modern Dance.md
_mk-at-yps/About Us/Contact Us.md

20240326_School Website Updates (CCA)

---

_our-community/Teaching Staff.md

- Removed Chua Mei Ling from 3 Respect under Teaching Staff page.

20240516_School Website Updates

---

_our-community/Executive Committee.md
_our-community/Non Teaching Staff.md
_our-community/Teaching Staff.md

- Added OM Chew Kah Leong under EXCO page.
- Added OSO Lim Heng Chye under Non-Teaching Staff page.
- Updated details under Teaching Staff page.

20240703_School Website Updates

---

_our-community/Teaching Staff.md

- Added Untrained Teachers Rick Ee, Wang Yi Ru and Tan Yuan Yang under the Teaching Staff page.

20240712_School Website Updates

---

_our-achievements/2024.md

- Updated details under Achievements 2024 page.

20240724_School Website Updates

---

_mk-at-yps/Our Staff.md
_quick-links/For Parents And Students.md

- Added YPS Bulletin newsletter Issue 3

20241106_School Website Updates

---

_mk-at-yps/Our Staff.md
_our-community/Executive Committee.md
_our-community/Non Teaching Staff.md
_our-community/Teaching Staff.md

- Add/remove staff from EXCO page.
- Add/remove staff from Teaching Staff Page.
- Add/remove staff from Non-Teaching Staff Page.
- Add/Remove Staff from MK Staff Page.

20241226_School Website Updates

---

_our-community/Executive Committee.md
_our-community/Teaching Staff.md

- Updated Elsie Kwan name and designated in EXCO and Teaching Staff page.

20241226_School Website Update (Part 1)

---

_our-community/Executive Committee.md

- Corrected Ms Pamela Wong email address link under EXCO webpage.

20241230_School Website Updates

---

_our-community/Executive Committee.md

20250116_School Website Updates Pt 2

---

_about-us/Calendar.md
_about-us/collection.yml
index.md

- Removed School Events Calendar page

20250131_School Website Updates

---

_mk-at-yps/MK Open House 2025.md
announcements/moe-kindergarten/_posts/2025-01-24-post-MK Open House 2025.md

- Added new videos under MK Open House page

20250210_School Website Update

---

pages/MOE Sexuality Education.md

- Updated MOE SED webpage as requested by Fauziah

20250225_School Website Updates

---

_our-community/Non Teaching Staff.md
_our-community/School Advisory Committee.md
_our-community/Teacher Leaders.md
_our-community/collection.yml

- Created Teacher Leaders page
- Updated SAC page
- Updated Non-Teaching Staff page

20250227_School Website Update

---

_signature-programme/LaunchPad@YPS.md

- Updated the snyopsis under LaunchPad@YPS page

20250704_School Website updates

---

index.md

- Removed the notification banner for Open House Announcement

20250709_School Website Updates

---

_quick-links/For Staff.md

- Added Edupage login link under Quick Links for Staff page.

20250804_School Website Updates Part 1

---

_our-community/Non Teaching Staff.md
_our-community/Teaching Staff.md

- Removed Thiviya, Yao Lingling and Eileen from Teaching Staff page.

20250828_School Website Updates 01

---

_about-us/Services In School/School Bookshop.md

- Updated contact information under School Bookshop.

20250901_School Website Updates 01

---

_quick-links/For Staff.md

- Added SEN Resource Portal (Intranet) under Quick Links for Staff page.

20250912_School Website Updates 01

---

_our-community/Executive Committee.md
_our-community/Teaching Staff.md

- Updated details in Teaching Staff page

20250930_School Website Updates 01
